name: Java CI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 16
    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
    - name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: Deploy to Sonatype Package Registry
      env:
        SONATYPE_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        SONATYPE_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>ossrh</id><username><![CDATA[${SONATYPE_USERNAME}]]></username><password><![CDATA[${SONATYPE_TOKEN}]]></password></server></servers></settings>" > ~/.m2/settings.xml
        mvn clean deploy -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
