name: Create Release
 
on:
  push:
    tags:
      - 'v*'
 
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Caching Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Project
        run: mvn package
      - name: Upload plugin artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true